Repository ataslangit/sistem-informasi-desa, pull requests merged in 2022-11, with the labels that each got.

#234 Perbaikan `CONTRIBUTING.md`
  .github/CONTRIBUTING.md
Labels: automerge

#236 Perbaikan GitHub Action workflows
  .github/workflows/automerge.yml
Labels: automerge, abaikan-rilis, admin

#238 Update automerge.yml
  .github/workflows/add_label.yml
  .github/workflows/automerge.yml
Labels: automerge

#239 Perbaikan workflows (test)
  .github/workflows/auto.yml
  .github/workflows/format-view.yml
  .github/workflows/format.yml
  .github/workflows/optimize-composer.yml
  .github/workflows/optimize.yml
  .github/workflows/phpcsfix.yml
Labels: automerge

#242 update auto.yml
  .github/workflows/auto.yml
Labels: automerge, abaikan-rilis, admin

#243 Tambahkan permission pada workflow (test)
  .github/workflows/auto.yml
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#237 Format `donjolib_helper.php`
  donjo-app/helpers/donjolib_helper.php
Labels: automerge

#244 TEST ganti ref: `${{ github.event.pull_request.head.ref }}`
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#246 TEST Update format.yml
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#247 TEST tambahkan repository
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#248 TEST Update format.yml
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#249 TEST Update format.yml
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#250 TEST Update format.yml
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#251 TEST Update format.yml
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#252 TEST
  .github/workflows/format.yml
Labels: automerge, abaikan-rilis, admin

#230 TEST Manual workflows
  .github/workflows/manual_format.yml
Labels: automerge, abaikan-rilis, admin

#256 Update workflows manual_format.yml
  .github/workflows/manual_format.yml
Labels: automerge

#257 TEST Update manual_format.yml
  .github/workflows/manual_format.yml
Labels: automerge, abaikan-rilis, admin

#259 hapus konstruktor kosong
  donjo-app/models/Analisis_grafik_model.php
  donjo-app/models/Analisis_indikator_model.php
  donjo-app/models/Analisis_kategori_model.php
  donjo-app/models/Analisis_klasifikasi_model.php
  donjo-app/models/Analisis_laporan_model.php
  donjo-app/models/Analisis_master_model.php
  donjo-app/models/Analisis_periode_model.php
  donjo-app/models/Analisis_statistik_jawaban_model.php
  donjo-app/models/Apis.php
  donjo-app/models/Config_model.php
  donjo-app/models/Export_model.php
  donjo-app/models/First_artikel_m.php
  donjo-app/models/First_gallery_m.php
  donjo-app/models/First_keluarga_m.php
  donjo-app/models/First_m.php
  donjo-app/models/First_menu_m.php
  donjo-app/models/First_penduduk_m.php
  donjo-app/models/First_slide_m.php
  donjo-app/models/Header_model.php
  donjo-app/models/Kelompok_master_model.php
  donjo-app/models/Kelompok_model.php
  donjo-app/models/Keluarga_model.php
  donjo-app/models/Laporan_penduduk_model.php
  donjo-app/models/Laporan_perubahan_model.php
  donjo-app/models/Mandiri_model.php
  donjo-app/models/Modul_model.php
  donjo-app/models/Pamong_model.php
  donjo-app/models/Penduduk_model.php
  donjo-app/models/Plan_area_model.php
  donjo-app/models/Plan_garis_model.php
  donjo-app/models/Plan_line_model.php
  donjo-app/models/Plan_lokasi_model.php
  donjo-app/models/Plan_point_model.php
  donjo-app/models/Plan_polygon_model.php
  donjo-app/models/Rtm_model.php
  donjo-app/models/Sms_model.php
  donjo-app/models/Surat_keluar_model.php
  donjo-app/models/Surat_master_model.php
  donjo-app/models/Surat_model.php
  donjo-app/models/Web_artikel_model.php
  donjo-app/models/Web_dokumen_model.php
  donjo-app/models/Web_gallery_model.php
  donjo-app/models/Web_kategori_model.php
  donjo-app/models/Web_komentar_model.php
  donjo-app/models/Web_menu_model.php
  donjo-app/models/Web_sosmed_model.php
  donjo-app/models/Web_statis_model.php
  donjo-app/models/Web_widget_model.php
  donjo-app/models/Wilayah_model.php
  donjo-sys/composer/installed.php
Labels: automerge, abaikan-rilis

#261 Tambahkan versi 4.x untuk laporan bug
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: automerge, abaikan-rilis

#262 tambahkan .devcontainer untuk codespaces
  .devcontainer/devcontainer.json
  .gitattributes
Labels: automerge, abaikan-rilis, admin

#263 hapus `donjo-app/models/Apis.php` karena tidak digunakan
  donjo-app/models/Apis.php
Labels: automerge

#264 gunakan `get_data()` langsung dari `config_model`
  donjo-app/controllers/First.php
  donjo-app/models/First_m.php
Labels: automerge

#265 gunakan config_model untuk pemanggilan config, cont. #264
  donjo-app/controllers/Area.php
  donjo-app/controllers/Garis.php
  donjo-app/controllers/Gis.php
  donjo-app/controllers/Keluarga.php
  donjo-app/controllers/Laporan.php
  donjo-app/controllers/Laporan_rentan.php
  donjo-app/controllers/Main.php
  donjo-app/controllers/Penduduk.php
  donjo-app/controllers/Plan.php
  donjo-app/controllers/Rtm.php
  donjo-app/controllers/Siteman.php
  donjo-app/controllers/Statistik.php
  donjo-app/controllers/Surat.php
  donjo-app/helpers/donjolib_helper.php
  donjo-app/models/Config_model.php
  donjo-app/models/Header_model.php
  donjo-app/models/Keluarga_model.php
  donjo-app/models/Laporan_bulanan_model.php
  donjo-app/models/Laporan_penduduk_model.php
  donjo-app/models/Laporan_perubahan_model.php
  donjo-app/models/Penduduk_model.php
  donjo-app/models/Plan_area_model.php
  donjo-app/models/Plan_garis_model.php
  donjo-app/models/Plan_lokasi_model.php
  donjo-app/models/Rtm_model.php
  donjo-app/models/Surat_model.php
  donjo-sys/composer/installed.php
Labels: automerge

#266 update changelog
  docs/changelog/dev.md
Labels: dokumentasi, automerge

#245 hapus fungsi `upgrade()` pada `config_model`
  donjo-app/models/Config_model.php
Labels: automerge, abaikan-rilis

#190 hapus fungsi `patch()` pada `config_model`
  donjo-app/models/Config_model.php
Labels: automerge

#187 hapus fungsi `kosong_web()` pada `config_model`
  donjo-app/models/Config_model.php
Labels: automerge

#198 hapus fungsi `get_id_user()` pada `header_model`
  donjo-app/models/Header_model.php
Labels: automerge

#37 Hapus fungsi `send_data()` pada `user_model`
  donjo-app/models/User_model.php
Labels: automerge

#268 penambahan Kategori model
  donjo-app/controllers/First.php
  donjo-app/controllers/Kategori.php
  donjo-app/controllers/Komentar.php
  donjo-app/controllers/Lapor.php
  donjo-app/controllers/Web.php
  donjo-app/models/First_artikel_m.php
  donjo-app/models/KategoriModel.php
  donjo-app/models/Web_artikel_model.php
  donjo-app/models/Web_kategori_model.php
  donjo-app/models/Web_komentar_model.php
  donjo-app/models/Web_statis_model.php
Labels: automerge

#271 tambahkan informasi untuk kontribusi
  .github/CONTRIBUTING.md
Labels: dokumentasi, automerge

#272 Penambahan info pull requests
  .github/CONTRIBUTING.md
Labels: dokumentasi, automerge

#232 hapus fungsi tak dipakai pada pict_helper
  donjo-app/helpers/pict_helper.php
Labels: automerge

#276 Tambahkan library install
  donjo-app/config/autoload.php
  donjo-app/controllers/Main.php
  donjo-app/helpers/donjolib_helper.php
  donjo-app/libraries/Install.php
  donjo-app/models/Config_model.php
Labels: automerge

#277 hapus duplikat load user_model
  donjo-app/controllers/Main.php
Labels: automerge

#255 Hapus load header_model pada siteman
  donjo-app/controllers/Siteman.php
Labels: automerge

#278 Load `config_model` pada helper dan model lain
  donjo-app/helpers/donjolib_helper.php
  donjo-app/models/Header_model.php
  donjo-app/models/Rtm_model.php
  donjo-app/models/User_model.php
Labels: automerge

#279 hapus `$this->load->database();`
  donjo-app/controllers/Area.php
  donjo-app/controllers/Garis.php
  donjo-app/controllers/Gis.php
  donjo-app/controllers/Line.php
  donjo-app/controllers/Plan.php
  donjo-app/controllers/Point.php
  donjo-app/controllers/Polygon.php
  donjo-app/models/Data_persil_model.php
  donjo-app/models/Feed_model.php
  donjo-app/models/Program_bantuan_model.php
Labels: automerge

#280 Tambahkan workflows `draft-release.yml`
  .github/workflows/draft-release.yml
Labels: automerge, abaikan-rilis, admin

#283 hapus fungsi tak dipakai pada User_model
  donjo-app/models/User_model.php
Labels: automerge
