Repository ataslangit/sistem-informasi-desa, pull requests merged in 2022-10, with the labels that each got.

#114 tambahkan exclude
  .github/release.yml
Labels: abaikan rilis

#117 perbaikan pada meta peruntukan halaman single
  donjo-app/views/layouts/header.php
Labels: bug

#119 Tampilkan FontAwesome icon pada frontend
  assets/css/font-awesome.css
  assets/css/font-awesome.min.css
  assets/fonts/FontAwesome.otf
  assets/fonts/fontawesome-webfont.eot
  assets/fonts/fontawesome-webfont.svg
  assets/fonts/fontawesome-webfont.ttf
  assets/fonts/fontawesome-webfont.woff
  assets/fonts/fontawesome-webfont.woff2
  donjo-app/views/layouts/header.php
Labels: bug

#122 Perbaikan sidebar pada layanan mandiri
  donjo-app/views/partials/side.right.php
Labels: bug

#124 penyesuaian config/
  donjo-app/config/autoload.php
  donjo-app/config/constants.php
  donjo-app/config/database.php
  donjo-app/config/foreign_chars.php
  donjo-app/config/hooks.php
  donjo-app/config/index.html
  donjo-app/config/migration.php
  donjo-app/config/profiler.php
  donjo-app/config/routes.php
  donjo-app/config/user_agents.php
Labels: peningkatan, abaikan-rilis

#126 tambahkan constant untuk versi SID ( `VERSI_SID` )
  donjo-app/config/constants.php
  donjo-app/views/feed.php
  donjo-app/views/home/about.php
  donjo-app/views/home/nav.php
  donjo-app/views/init.php
  donjo-app/views/install.php
  donjo-app/views/siteman.php
Labels: peningkatan, abaikan-rilis

#128 Tambahkan `.gitignore`
  .gitattributes
  .gitignore
Labels: abaikan-rilis, admin

#127 Tambahkan `.editorconfig`
  .editorconfig
  .gitattributes
Labels: abaikan-rilis, admin

#138 Perbaikan pada form tambah kelompok baru
  donjo-app/views/kelompok/form.php
Labels: bug, perbaikan

#139 Penambahan code_of_conduct.md
  .gitattributes
  code_of_conduct.md
Labels: abaikan-rilis, admin

#143 Perbaiki ikon fa-plus menggantikan icon-plus
  app/views/kategori/table.php
  app/views/menu/table.php
  app/views/sid/kependudukan/keluarga_statistik.php
Labels: bug, perbaikan

#146 Perbarui constant `VERSI_SID`
  app/config/constants.php
Labels: abaikan-rilis, admin

#147 Penambahan file dotEnv untuk pengaturan tambahan
  .gitignore
  app/config/database.php
  composer.json
  env
  index.php
  vendor/autoload.php
  vendor/vlucas/phpdotenv/src/Dotenv.php
  vendor/vlucas/phpdotenv/src/Exception/ExceptionInterface.php
  vendor/vlucas/phpdotenv/src/Exception/InvalidEncodingException.php
  vendor/vlucas/phpdotenv/src/Exception/InvalidFileException.php
  vendor/vlucas/phpdotenv/src/Exception/InvalidPathException.php
  vendor/vlucas/phpdotenv/src/Exception/ValidationException.php
  vendor/vlucas/phpdotenv/src/Loader/Loader.php
  vendor/vlucas/phpdotenv/src/Loader/LoaderInterface.php
  vendor/vlucas/phpdotenv/src/Loader/Resolver.php
  vendor/vlucas/phpdotenv/src/Parser/Entry.php
  vendor/vlucas/phpdotenv/src/Parser/EntryParser.php
  vendor/vlucas/phpdotenv/src/Parser/Lexer.php
  vendor/vlucas/phpdotenv/src/Parser/Lines.php
  vendor/vlucas/phpdotenv/src/Parser/Parser.php
  vendor/vlucas/phpdotenv/src/Parser/ParserInterface.php
  vendor/vlucas/phpdotenv/src/Parser/Value.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/AdapterInterface.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/ApacheAdapter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/ArrayAdapter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/EnvConstAdapter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/GuardedWriter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/ImmutableWriter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/MultiReader.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/MultiWriter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/PutenvAdapter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/ReaderInterface.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/ReplacingWriter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/ServerConstAdapter.php
  vendor/vlucas/phpdotenv/src/Repository/Adapter/WriterInterface.php
  vendor/vlucas/phpdotenv/src/Repository/AdapterRepository.php
  vendor/vlucas/phpdotenv/src/Repository/RepositoryBuilder.php
  vendor/vlucas/phpdotenv/src/Repository/RepositoryInterface.php
  vendor/vlucas/phpdotenv/src/Store/File/Paths.php
  vendor/vlucas/phpdotenv/src/Store/File/Reader.php
  vendor/vlucas/phpdotenv/src/Store/FileStore.php
  vendor/vlucas/phpdotenv/src/Store/StoreBuilder.php
  vendor/vlucas/phpdotenv/src/Store/StoreInterface.php
  vendor/vlucas/phpdotenv/src/Store/StringStore.php
  vendor/vlucas/phpdotenv/src/Util/Regex.php
  vendor/vlucas/phpdotenv/src/Util/Str.php
  vendor/vlucas/phpdotenv/src/Validator.php
Labels: peningkatan, dependencies

#149 jangan abaikan composer autoload
  .gitignore
  composer.json
  vendor/composer/ClassLoader.php
  vendor/composer/InstalledVersions.php
  vendor/composer/LICENSE
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_namespaces.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/composer/platform_check.php
Labels: abaikan-rilis, perbaikan

#150 Fix problem load
  .gitignore
  app/helpers/donjolib_helper.php
  app/helpers/pict_helper.php
  vendor/autoload.php
  vendor/composer/LICENSE
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.php
  vendor/graham-campbell/result-type/src/Error.php
  vendor/graham-campbell/result-type/src/Result.php
  vendor/graham-campbell/result-type/src/Success.php
  vendor/phpoption/phpoption/src/PhpOption/LazyOption.php
  vendor/phpoption/phpoption/src/PhpOption/None.php
  vendor/phpoption/phpoption/src/PhpOption/Option.php
  vendor/phpoption/phpoption/src/PhpOption/Some.php
  vendor/symfony/polyfill-ctype/Ctype.php
  vendor/symfony/polyfill-ctype/bootstrap.php
  vendor/symfony/polyfill-ctype/bootstrap80.php
  vendor/symfony/polyfill-mbstring/Mbstring.php
  vendor/symfony/polyfill-mbstring/Resources/unidata/lowerCase.php
  vendor/symfony/polyfill-mbstring/Resources/unidata/titleCaseRegexp.php
  vendor/symfony/polyfill-mbstring/Resources/unidata/upperCase.php
  vendor/symfony/polyfill-mbstring/bootstrap.php
  vendor/symfony/polyfill-mbstring/bootstrap80.php
  vendor/symfony/polyfill-php80/Php80.php
  vendor/symfony/polyfill-php80/PhpToken.php
  vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php
  vendor/symfony/polyfill-php80/Resources/stubs/PhpToken.php
  vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php
  vendor/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php
  vendor/symfony/polyfill-php80/Resources/stubs/ValueError.php
  vendor/symfony/polyfill-php80/bootstrap.php
Labels: bug, abaikan-rilis, dependencies

#153 Tambahkan nilai default untuk `$offset` & `$limit`
  donjo-app/models/First_artikel_m.php
Labels: bug, perbaikan

#155 Update deploy.yml
  .github/workflows/deploy.yml
Labels: abaikan-rilis, admin

#158 Create config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: abaikan-rilis, admin

#159 Perbaikan docs
  docs/.vitepress/config.js
  docs/index.md
  docs/panduan/index.md
  docs/panduan/migrasi-dari-v310-cri.md
  docs/panduan/mulai.md
  docs/panduan/persyaratan-server.md
  docs/tentang.md
  package-lock.json
  package.json
Labels: dokumentasi, abaikan-rilis
